users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import (
    login,
    logout,
    register,
    profile,
    user_cart,
)

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('registration/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('user_cart/', user_cart, name='user_cart'),
]





users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    session_key = models.CharField(max_length=32, unique=True, blank=True, null=True, verbose_name='Временная регистрация')
    image = models.ImageField(
        upload_to='users_images',
        blank=True,
        null=True,
        verbose_name='Аватар',
    )

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

users/forms.py
from django import forms

from users.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm


class UserLoginForm(AuthenticationForm):

    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User
        fields = [
            'username',
            'password',
        ]


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        ]


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = [
            'image',
            'first_name',
            'last_name',
            'username',
            'email',
        ]

users/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView

from goods.models import Category
from .forms import UserLoginForm, UserRegisterForm, ProfileForm
from .models import User
from django.contrib import auth, messages


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()  # Сохраняем форму и получаем объект пользователя
            messages.success(request, 'Успешная регистрация и вход.')
            auth.login(request, user)  # Логиним пользователя
            return redirect(reverse('goods:catalogs'))
    else:
        form = UserRegisterForm()

    context = {
        'title': 'Регистрация',
        'form': form
    }

    return render(request, 'users/register.html', context)


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                messages.success(request, 'Вы вошли в аккаунт.')

                redirect_page = request.POST.get('next', None)
                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.POST.get('next'))

                return HttpResponseRedirect(reverse('goods:catalogs'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'savannah - Авторизация',
        'form': form
    }

    return render(request, 'users/login.html', context)


@login_required
def logout(request):
    messages.success(request, 'Вы вышли из аккаунта.')
    auth.logout(request)
    return redirect('goods:catalogs')


@login_required
def profile(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Профиль обновлен.')
            return redirect(reverse('users:profile'))
    else:
        form = ProfileForm(instance=request.user)

    context = {
        'title': 'Профиль',
        'form': form,
        'categories': categories,
    }

    return render(request, 'users/profile.html', context)


# Cart
def user_cart(request):
    return render(request, 'users/cart.html')

users/templates/includes/notifications.html
{% load static %}


{% if form.non_field_errors %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">
                    {{ form.non_field_errors }}
                </div>
            </div>
        </div>
    </div>
{% endif %}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow">
                            {{ message }}
                        </div>
                    {% endif %}
                    {% if message.tags == 'warning' %}
                        <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-danger fade show custom-shadow">
                            {{ message }}
                        </div>
                    {% endif %}
                {% endfor %}
            {% else %}
                <div id="jq-notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow">
                </div>
            {% endif %}
        </div>
    </div>
</div>

users/templates/users/cart.html
{% extends 'main/index.html' %}
{% load static %}
{% load cart_tags %}

{% block css %}
    <!-- Bootstrap CSS -->
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link href="{% static 'main/css/tiny-slider.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
    <title>Cart - Your Store</title>
    <style>
        .empty-cart-message {
            text-align: center;
            margin-top: 50px;
        }
        .empty-cart-message h3 {
            font-size: 24px;
            margin-bottom: 20px;
        }
        .empty-cart-message h4 {
            font-size: 20px;
        }
        .empty-cart-message .btn {
            background-color: #000;
            color: #fff;
            padding: 10px 20px;
            font-size: 18px;
            text-decoration: none;
        }
        .empty-cart-message .btn:hover {
            background-color: #555;
        }
    </style>
{% endblock css %}

{% block content %}
{% user_carts request as carts %}

{% if carts %}
<div class="untree_co-section before-footer-section">
    <div class="container">
        <div class="row mb-5">
            <form class="col-md-12" method="post">
                <div class="site-blocks-table">
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="product-thumbnail">Image</th>
                                <th class="product-name">Product</th>
                                <th class="product-price">Price</th>
                                <th class="product-quantity">Quantity</th>
                                <th class="product-total">Total</th>
                                <th class="product-remove">Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for cart in carts %}
                        <tr data-product-slug="{{ cart.product.id }}">
                            <td class="product-thumbnail">
                                <img src="{{ cart.product.image.url }}" alt="Image" class="img-fluid">
                            </td>
                            <td class="product-name">
                                <h2 class="h5 text-black">{{ cart.product.name }}</h2>
                            </td>
                            <td>${{ cart.product.sell_price }}</td>
                            <td>
                                <div class="input-group mb-3 d-flex align-items-center quantity-container" style="max-width: 120px;">
                                    <div class="input-group-prepend">
                                        <button class="btn btn-outline-black decrease" type="button">&minus;</button>
                                    </div>
                                    <input type="text" class="form-control text-center quantity-amount" value="{{ cart.quantity }}" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                                    <div class="input-group-append">
                                        <button class="btn btn-outline-black increase" type="button">&plus;</button>
                                    </div>
                                </div>
                            </td>
                            <td class="product-total">${{ cart.products_price }}</td>
                            <td>
                                <form class="delete-form" action="{% url 'cart:cart_delete' cart.id %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-black btn-sm">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            </form>

                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </form>
        </div>

                    {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

        <div class="row">
            <div class="col-md-6">
                <div class="row mb-5">
                    <div class="col-md-6 mb-3 mb-md-0">
                        <button class="btn btn-black btn-sm btn-block">Update Cart</button>
                    </div>
                    <div class="col-md-6">
                        <button class="btn btn-outline-black btn-sm btn-block">Continue Shopping</button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label class="text-black h4" for="coupon">Coupon</label>
                        <p>Enter your coupon code if you have one.</p>
                    </div>
                    <div class="col-md-8 mb-3 mb-md-0">
                        <input type="text" class="form-control py-3" id="coupon" placeholder="Coupon Code">
                    </div>
                    <div class="col-md-4">
                        <button class="btn btn-black">Apply Coupon</button>
                    </div>
                </div>
            </div>
            <div class="col-md-6 pl-5">
                <div class="row justify-content-end">
                    <div class="col-md-7">
                        <div class="row">
                            <div class="col-md-12 text-right border-bottom mb-5">
                                <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                            </div>
                        </div>
                        <div class="row mb-5">
                            <div class="col-md-6">
                                <span class="text-black">Total</span>
                            </div>
                            <div class="col-md-6 text-right">
                                <strong class="text-black">${{ carts.total_price }}</strong>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <button class="btn btn-black btn-lg py-3 btn-block" onclick="window.location='checkout.html'">Proceed To Checkout</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="empty-cart-message">
    <h3>Товаров нет в корзине</h3>
    <h4><a href="{% url 'goods:catalogs' %}" class="btn">Перейти на главную</a></h4>
</div>
{% endif %}

<script src="{% static 'main/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'main/js/tiny-slider.js' %}"></script>
<script src="{% static 'main/js/custom.js' %}"></script>

{% endblock %}

users/templates/users/login.html

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'users/css/login_style.css' %}">
{% endblock css %}

{% block content %}
<div class="login-container">
    <h3>Авторизация</h3>
    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        {% if form.non_field_errors %}
            <p class="error">{{ form.non_field_errors }}</p>
        {% endif %}

        <div class="mb-3">
            <label for="id_username" class="form-label">Имя пользователя</label>
            <input type="text" class="form-control" name="username" placeholder="Введите имя">
        </div>
        <div class="mb-3">
            <label for="id_password" class="form-label">Пароль</label>
            <input type="password" class="form-control" name="password" id="id_password" placeholder="Введите пароль">
        </div>
        <button type="submit" class="btn btn-primary">Войти</button>
        <div class="additional-links">
            <a href="{% url 'users:register' %}" class="btn btn-secondary">Зарегистрироваться</a>
            {% comment %}<a href="{% url 'users:password_reset' %}" class="btn btn-link">Забыли пароль?</a>{% endcomment %}
            <a href="#" class="btn btn-google"><i class="fa fa-google"></i> Войти с Google</a>
        </div>
    </form>
</div>
{% endblock content %}

users/templates/users/profile.html
{% extends 'main/index.html' %}
{% load static %}

{% block css %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Профиль пользователя</title>
    <link rel="stylesheet" href="{% static 'users/css/profile.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <header class="profile-header">
            <h1>Мой профиль</h1>
        </header>
        <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
        <div class="profile-content">
            <div class="profile-sidebar">
                <div class="avatar">
                    {% if user.image %}
                        <img src="{{ user.image.url }}" alt="Аватар">
                    {% else %}
                        <img src="{% static 'users/img/default_image.png' %}" alt="Аватар">
                    {% endif %}
                    <div class="form-group">
                        <label for="image">Аватар</label>
                        <input type="file" name="image" id="id_image">
                    </div>
                </div>
                <ul>
                   <li class="nav-item active"><a href="{% url 'goods:catalogs' %}">Каталог</a></li>
                    <li><a href="#orders">Мои заказы</a></li>
                    <li><a href="{% url 'users:logout' %}">Выйти</a></li>
                </ul>
            </div>
            <div class="profile-main">
                <section id="edit">

                        {% csrf_token %}
                        <div class="form-group">
                            <label for="first_name">Имя</label>
                            <input type="text" name="first_name" id="first_name" value="{{ user.first_name }}">
                        </div>
                        <div class="form-group">
                            <label for="last_name">Фамилия</label>
                            <input type="text" name="last_name" id="last_name" value="{{ user.last_name }}">
                        </div>
                        <div class="form-group">
                            <label for="email">Электронная почта</label>
                            <input type="email" name="email" id="email" value="{{ user.email }}">
                        </div>
                        <div class="form-group">
                            <label for="username">Имя пользователя</label>
                            <input type="text" name="username" id="username" value="{{ user.username }}">
                        </div>

                        <button type="submit" class="btn btn-primary">Сохранить изменения</button>
                    </form>
                </section>

                <section id="orders">
                    <h2>Мои заказы</h2>
                    <!-- Пример заказов, замените на реальные данные -->
                    <ul>
                        <li>Заказ #1 - Статус: Доставлен</li>
                        <li>Заказ #2 - Статус: В пути</li>
                        <li>Заказ #3 - Статус: Ожидает оплаты</li>
                    </ul>
                </section>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/register.html


{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'users/css/register_style.css' %}">
{% endblock css %}

{% block content %}
    <div class="container">
        <div class="form-container">
            <h2>Регистрация</h2>
            <form action="{% url 'users:register' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Зарегистрироваться</button>
            </form>
        </div>
    </div>
{% endblock %}