crud_app/urls.py
from django.urls import path
from . import views
from .views import ( ProductDeleteView,
ProductDetailView, ProductUpdateView,
)


app_name = 'crud_app'

urlpatterns = [
    # path('create', ProductCreateView.as_view(), name='create_product'),
    path('delete/<slug:product_slug>/', ProductDeleteView.as_view(), name='delete_product'),
    path('update/<slug:product_slug>/', ProductUpdateView.as_view(), name='update_product'),
    path('product/<slug:product_slug>/', ProductDetailView.as_view(), name='detail_product'),
]

crud_app/forms.py
from django import forms
from goods.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product

        fields = [
            'name',
            'description',
            'quantity',
            'price',
            'stock',
            'discount',
            'category',

            'image'
        ]





crud_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView
from .forms import ProductForm
from goods.models import Product


# Product - views
class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'crud_app/detail_product.html'
    slug_field = 'slug'
    slug_url_kwarg = 'product_slug'


# class ProductsCreateView(CreateView):
#     model = Products
#     form_class = ProductForm
#     template_name = 'crud_app/create_product.html'


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'crud_app/update_product.html'
    slug_field = 'slug'
    slug_url_kwarg = 'product_slug'


class ProductDeleteView(DeleteView):
    model = Product
    context_object_name = 'product'
    template_name = 'crud_app/delete_product.html'
    success_url = reverse_lazy('goods:catalogs')
    slug_field = 'slug'
    slug_url_kwarg = 'product_slug'









crud_app/templates/crud_app/create_product.html
{% extends 'main/index.html' %}
{% load static %}


    {% block title %}
        <title>Create Product</title>
    {% endblock title %}

    {% block style %}
        <link rel="stylesheet" href="{% static 'crud_app/css/style_create.css' %}">
    {% endblock style %}

    {% block content %}
        <div class="news-form">
            <h2>Create Product</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    {% endblock content %}



crud_app/templates/crud_app/delete_product.html
{% extends 'main/index.html' %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href="{% static 'crud_app/css/style_delete.css' %}">
{% endblock css %}


{% block content %}
<br>
<br>
<form method="post">
    {% csrf_token %}
    <div class="container">
        <h2>Вы уверены, что хотите удалить этот товар?</h2>
        <p>Название: {{ product.title }}</p>
        <p>Описание: {{ product.description }}</p>
        <form action="{% url 'crud_app:delete_product' product.slug %}" method="post">
            {% csrf_token %}
            <button type="submit" class="delete-btn">Удалить</button>
            <a href="{% url 'crud_app:detail_product' product.slug %}" class="cancel-btn">Отмена</a>
        </form>
    </div>
</form>

{% endblock content %}

crud_app/templates/crud_app/detail_product.html
{% extends 'main/index.html' %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href="{% static 'crud_app/css/style_detail.css' %}">
{% endblock css %}


{% block content %}
<br>
<br>
    <div class="container">
        <h2>{{ product.name }}</h2>
            <p>Категория: {{ product.category }}</p>
            <p class="date">Дата публикации: {{ product.created_at }}</p>
            <p class="description">{{ product.description }}</p>
            <div class="content">{{ product.price }}</div>
        <img src="{{ product.image.url }}" alt="{{ product.name }}">
        <a class="nav-link icon-cross" href="{% url 'cart:cart_add' product.id %}">
            <img src="{% static 'goods/images/cross.svg' %}" class="img-fluid">
        </a>
    </div>

<br>

{% endblock content %}







crud_app/templates/crud_app/update_product.html
{% extends 'main/index.html' %}
{% load static %}

{% block title %}
    <title>Редактирование продукта</title>
{% endblock title %}
{% block css %}
    <link rel="stylesheet" href="{% static 'crud_app/css/style_update.css' %}">
{% endblock css %}
{% block content %}
    <div class="container">
        <h2>Редактирование продукта</h2>
        <form action="{% url 'crud_app:update_product' product.slug %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="update-btn">Обновить продукт</button>
            <a href="{% url 'crud_app:detail_product' product.slug %}" class="cancel-btn">Отмена</a>
        </form>
    </div>
{% endblock content %}